#!/bin/bash
# PostToolUse(Write|Edit): when Claude writes a dependency manifest or lockfile,
# remind it to verify the versions are current (Claude's training data goes stale,
# so pinned versions written from memory are often outdated). Advisory only —
# emits additionalContext and always exits 0, never blocks the write.
#
# Reminder-only by design: the hook does NOT hit any package registry. It tells
# Claude *to* look up the latest versions, with the right command per ecosystem;
# Claude does the actual checking.
#
# Opt out per repo/user with DEV_HOOKS_LATEST_DEPS=false (in .claude settings "env").

case "${DEV_HOOKS_LATEST_DEPS:-}" in
  false|0|no|off) exit 0 ;;
esac

INPUT=$(cat 2>/dev/null)
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
[ -z "$FILE" ] && exit 0
SESSION=$(printf '%s' "$INPUT" | jq -r '.session_id // "nosession"' 2>/dev/null)

BASE=$(basename "$FILE")

# Classify by basename. Lockfiles first so e.g. package-lock.json isn't caught by
# the package.json (js) arm.
CATEGORY=""
case "$BASE" in
  package-lock.json|yarn.lock|pnpm-lock.yaml|bun.lockb|bun.lock|Gemfile.lock|poetry.lock|uv.lock|Pipfile.lock)
    CATEGORY="lockfile" ;;
  requirements*.txt|requirements*.in|constraints*.txt|pyproject.toml|setup.py|setup.cfg|Pipfile)
    CATEGORY="python" ;;
  package.json)
    CATEGORY="js" ;;
  Gemfile|*.gemspec)
    CATEGORY="ruby" ;;
  *)
    exit 0 ;;
esac

# Fire at most once per (session x category) so repeated edits don't re-nag.
MARKER_DIR="${TMPDIR:-/tmp}/dev-hooks-latest-deps"
mkdir -p "$MARKER_DIR" 2>/dev/null
MARKER="$MARKER_DIR/${SESSION}-${CATEGORY}"
[ -e "$MARKER" ] && exit 0
: > "$MARKER" 2>/dev/null

LEAD="You just wrote $BASE. Your training data may be stale, so do NOT trust pinned versions from memory."

case "$CATEGORY" in
  python)
    MSG="$LEAD Verify each pinned dependency is the current stable release before finalizing. Check the latest with \`pip index versions <pkg>\` or \`uv pip index versions <pkg>\` (or https://pypi.org/project/<pkg>). Prefer the latest stable unless a specific constraint requires an older version." ;;
  js)
    MSG="$LEAD Verify each dependency version is current before finalizing. Check the latest with \`npm view <pkg> version\`. Prefer the latest stable unless a specific constraint requires an older version." ;;
  ruby)
    MSG="$LEAD Verify each gem version is current before finalizing. Check the latest with \`gem search -r <gem>\` (or https://rubygems.org/gems/<gem>). Prefer the latest stable unless a specific constraint requires an older version." ;;
  lockfile)
    MSG="$LEAD This is a lockfile — it should be generated by the package manager, not hand-written or hand-pinned. Regenerate it with the appropriate tool (\`npm install\`, \`bundle install\`, \`uv lock\`, \`poetry lock\`, etc.) so versions resolve to current, mutually compatible releases." ;;
esac

jq -cn --arg msg "$MSG" '{hookSpecificOutput: {hookEventName: "PostToolUse", additionalContext: $msg}}'
exit 0
