#!/bin/bash
# PostToolUse(Write|Edit): when Claude writes a dependency manifest or lockfile,
# remind it to verify the versions are current (Claude's training data goes stale,
# so pinned versions written from memory are often outdated). Advisory only —
# emits additionalContext and always exits 0, never blocks the write.
#
# Reminder-only by design: the hook does NOT hit any package registry. It tells
# Claude *to* look up the latest versions, with the right command per ecosystem;
# Claude does the actual checking.
#
# Opt out per repo/user with DEV_HOOKS_LATEST_DEPS=false (in .claude settings "env").

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=lib/reminder-common.sh
source "$SELF_DIR/lib/reminder-common.sh"
# Sets INPUT, FILE, SESSION, BASE (or exits 0 on opt-out / missing file_path).
reminder_init DEV_HOOKS_LATEST_DEPS

# Classify by basename. Lockfiles first so e.g. package-lock.json isn't caught by
# the package.json (js) arm.
CATEGORY=""
case "$BASE" in
  package-lock.json | yarn.lock | pnpm-lock.yaml | bun.lockb | bun.lock | Gemfile.lock | poetry.lock | uv.lock | Pipfile.lock)
    CATEGORY="lockfile"
    ;;
  requirements*.txt | requirements*.in | constraints*.txt | pyproject.toml | setup.py | setup.cfg | Pipfile)
    CATEGORY="python"
    ;;
  package.json)
    CATEGORY="js"
    ;;
  Gemfile | *.gemspec)
    CATEGORY="ruby"
    ;;
  *)
    exit 0
    ;;
esac

# Fire at most once per (session x category) so repeated edits don't re-nag.
reminder_fire_once latest-deps "$CATEGORY" || exit 0

LEAD="You just wrote $BASE. Your training data may be stale, so do NOT trust pinned versions from memory."

# Appended to manifest (not lockfile) messages: keep human-facing docs in sync with the
# versions just written. Lockfiles are excluded — they're regenerated, not where versions
# are authored.
DOCS_TRAILER=" Also keep the human-facing docs in sync: update README.md and CLAUDE.md (create them if they don't exist) to record the current versions of key packages (main framework, Tailwind, Bootstrap, etc.). Updating both is preferred."

case "$CATEGORY" in
  python)
    MSG="$LEAD Verify each pinned dependency is the current stable release before finalizing. Check the latest with \`pip index versions <pkg>\` or \`uv pip index versions <pkg>\` (or https://pypi.org/project/<pkg>). Prefer the latest stable unless a specific constraint requires an older version.$DOCS_TRAILER"
    ;;
  js)
    MSG="$LEAD Verify each dependency version is current before finalizing. Check the latest with \`npm view <pkg> version\`. Prefer the latest stable unless a specific constraint requires an older version.$DOCS_TRAILER"
    ;;
  ruby)
    MSG="$LEAD Verify each gem version is current before finalizing. Check the latest with \`gem search -r <gem>\` (or https://rubygems.org/gems/<gem>). Prefer the latest stable unless a specific constraint requires an older version.$DOCS_TRAILER"
    ;;
  lockfile)
    MSG="$LEAD This is a lockfile — it should be generated by the package manager, not hand-written or hand-pinned. Regenerate it with the appropriate tool (\`npm install\`, \`bundle install\`, \`uv lock\`, \`poetry lock\`, etc.) so versions resolve to current, mutually compatible releases."
    ;;
esac

reminder_emit "$MSG"
