#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Automate the common-case .env -> fnox migration SKILL.md walks through by hand.

For the Bitwarden Secrets Manager provider (this skill's default): parses a `.env`
file, creates one Secrets Manager secret per variable via `bws secret create <key>
<value> <project-id>` (the exact invocation documented in the skill's step 3), and
writes a `fnox.toml` with `[providers]`/`[secrets]` reference-only entries (step 4's
shape) -- never a secret value. `--verify` then confirms each key resolves via
`fnox get -c <output> <KEY>` (step 7 / Guardrails), and `--delete-source` removes the
original `.env` once confirmed -- gated behind a typed "DELETE" prompt.

This is a shortcut for the common case, not a replacement for the manual walkthrough:
non-secret config, multiple `.env.*` files, and the Password Manager variant still
need the judgement calls SKILL.md describes.

Usage:
  migrate_env_to_fnox.py --env-file .env --project-id <PROJECT_ID> [--output fnox.toml]
                          [--dry-run] [--verify] [--delete-source]

Exit code: 0 = success (including a --dry-run preview), 1 = a dotenv/bws/fnox/
confirmation error, 2 = a command-line usage error (argparse).
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

PROVIDER_NAME = "bws"

# Mirrors the upstream Ruby dotenv rules exactly: a bare unquoted value, a single-quoted
# literal, or a double-quoted value with only \\ and \" escapes -- anything else aborts
# rather than guessing at shell-like expansion this isn't actually doing.
_KEY_RE = re.compile(r"\A([A-Za-z_][A-Za-z0-9_]*)=(.*)\Z")
_BARE_RE = re.compile(r"""\A[^\s#'"`$\\]+\Z""")
_SINGLE_RE = re.compile(r"\A'[^']*'\Z")
_DOUBLE_RE = re.compile(r'\A"(?:[^"\\$`]|\\[\\"])*"\Z')
_DOUBLE_ESCAPE_RE = re.compile(r'\\([\\"])')
_PROJECT_ID_RE = re.compile(r"\A[A-Za-z0-9-]+\Z")


class DotenvError(Exception):
    """A single-line, user-facing message about unsupported/malformed dotenv syntax."""


def parse_dotenv_value(raw: str, line_no: int) -> str:
    """Decode one RHS per the rules above; raises DotenvError on anything else."""
    if raw == "" or _BARE_RE.fullmatch(raw):
        return raw
    if _SINGLE_RE.fullmatch(raw):
        return raw[1:-1]
    if _DOUBLE_RE.fullmatch(raw):
        return _DOUBLE_ESCAPE_RE.sub(r"\1", raw[1:-1])
    raise DotenvError(f"Unsupported dotenv value syntax on line {line_no}")


def parse_dotenv(path: Path) -> dict[str, str]:
    """Parse a .env file into {KEY: value}. Blank lines and full-line `#` comments are
    skipped; a key repeated later in the file overwrites the earlier value (last wins,
    matching the upstream Ruby port). Pure and subprocess-free -- exercised directly by
    running the whole CLI under --dry-run."""
    values: dict[str, str] = {}
    for i, line in enumerate(Path(path).read_text().splitlines(), start=1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = _KEY_RE.fullmatch(line)
        if not m:
            raise DotenvError(f"Unsupported dotenv syntax on line {i}")
        values[m.group(1)] = parse_dotenv_value(m.group(2), i)
    return values


def bws_key_name(env_key: str) -> str:
    """DATABASE_URL -> database-url, the key-name convention SKILL.md's step 3 uses."""
    return env_key.lower().replace("_", "-")


def _toml_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_fnox_toml(values: dict[str, str], project_id: str) -> str:
    """Build the fnox.toml text SKILL.md's step 4 documents by hand: a `[providers]`
    table with one `bitwarden-sm` entry, and a `[secrets]` table of ENV_VAR = {
    provider, value = key-name } rows. `value` is always the Secrets Manager KEY NAME,
    never the secret itself -- fnox.toml holds only references. Pure string-building,
    no I/O."""
    lines = [
        "# Generated by migrate_env_to_fnox.py -- references only, no secret values.",
        "[providers]",
        f'{PROVIDER_NAME} = {{ type = "bitwarden-sm", project_id = {_toml_string(project_id)} }}',
        "",
        "[secrets]",
    ]
    for key, _ in values.items():
        lines.append(
            f"{key} = {{ provider = {_toml_string(PROVIDER_NAME)}, "
            f"value = {_toml_string(bws_key_name(key))} }}"
        )
    lines.append("")
    return "\n".join(lines)


# --- thin, mockable subprocess wrappers -------------------------------------------
# Kept to a single subprocess.run call each so tests can put a stub `bws`/`fnox` first
# on PATH (or, when embedding this module, monkeypatch the function directly) rather
# than needing a real Bitwarden account.


def run_bws_secret_create(key_name, value, project_id, bws_bin="bws"):
    """`bws secret create <key> <value> <project-id>` -- SKILL.md step 3's exact form."""
    return subprocess.run(
        [bws_bin, "secret", "create", key_name, value, project_id],
        capture_output=True,
        text=True,
    )


def run_fnox_get(env_key, config_path, fnox_bin="fnox"):
    """`fnox get -c <config> <KEY>` -- the config-scoped resolution SKILL.md's
    Guardrails section documents, pointed at the freshly written fnox.toml."""
    return subprocess.run(
        [fnox_bin, "get", "-c", str(config_path), env_key],
        capture_output=True,
        text=True,
    )


def die(message: str, code: int = 1) -> int:
    print(f"migrate_env_to_fnox: {message}", file=sys.stderr)
    return code


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Migrate a .env file to fnox + Bitwarden Secrets Manager, "
        "automating the steps env-to-fnox/SKILL.md documents by hand."
    )
    p.add_argument("--env-file", required=True, help="path to the .env file to migrate")
    p.add_argument(
        "--project-id",
        required=True,
        help="Bitwarden Secrets Manager project ID (the vault scope for `bws`)",
    )
    p.add_argument(
        "--output",
        default="fnox.toml",
        help="path to write the generated fnox.toml (default: fnox.toml)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="print what would be migrated; makes no bws/fnox calls and writes nothing",
    )
    p.add_argument(
        "--verify",
        action="store_true",
        help="after writing fnox.toml, confirm each secret resolves via `fnox get`",
    )
    p.add_argument(
        "--delete-source",
        action="store_true",
        help="remove --env-file once migrated (asks for a typed DELETE confirmation)",
    )
    return p


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)

    if not _PROJECT_ID_RE.fullmatch(args.project_id):
        return die("--project-id may contain only letters, numbers, and hyphens")

    env_path = Path(args.env_file)
    if not env_path.exists():
        return die(f"no such file: {args.env_file}")

    try:
        values = parse_dotenv(env_path)
    except DotenvError as e:
        return die(str(e))

    if not values:
        return die("no dotenv assignments found")

    if args.dry_run:
        print(f"Would migrate {len(values)} variable(s): {', '.join(sorted(values))}")
        return 0

    bws_bin = shutil.which("bws")
    if not bws_bin:
        return die(
            "bws CLI not found on PATH (run `mise use -g fnox "
            "bitwarden-secrets-manager` per SKILL.md step 2)"
        )

    for key, value in values.items():
        key_name = bws_key_name(key)
        result = run_bws_secret_create(key_name, value, args.project_id, bws_bin)
        if result.returncode != 0:
            return die(
                f"bws secret create failed for {key} ({key_name}): "
                f"{result.stderr.strip() or result.stdout.strip()}"
            )
        print(f"Created secret: {key_name}  ({key})")

    output_path = Path(args.output)
    output_path.write_text(render_fnox_toml(values, args.project_id))
    output_path.chmod(0o600)
    print(f"Wrote {output_path}")

    if args.verify:
        fnox_bin = shutil.which("fnox")
        if not fnox_bin:
            return die("fnox CLI not found on PATH (see SKILL.md step 2)")
        failed = []
        for key in values:
            result = run_fnox_get(key, output_path, fnox_bin)
            if result.returncode != 0 or not result.stdout.strip():
                failed.append(key)
        if failed:
            return die(
                f"verification failed for: {', '.join(failed)} -- check "
                "BWS_ACCESS_TOKEN is set and the provider/project-id match "
                "(see SKILL.md step 7)"
            )
        print(f"Verified {len(values)} secret(s) resolve via fnox.")

    if args.delete_source:
        answer = input(f'Type DELETE to remove "{env_path}": ')
        if answer != "DELETE":
            return die(
                f"confirmation did not match -- {env_path} was NOT deleted "
                "(the secrets and fnox.toml above were already written)"
            )
        env_path.unlink()
        print(f"Removed {env_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
